### ISSUE TITLE
vscode generates empty image

### ISSUE THREAD

**Issue by sodiumnitrate** [nglviewer/nglview#1091]
I'm using vscode to edit `.ipynb` files. I'm also using `pyenv` to manage my python versions. I'm using `3.11.2`, and have set my jupyter notebook kernel accordingly. I have:

```python
import nglview as nv
import ipywidgets

view = nv.show_pdbid("3pqr")
view
```
but only a thin white image with no apparent content shows up. I verify I'm using the correct python version within the notebook:

```python
import sys
print(sys.version)
import os
print(os.system("pyenv which python"))
```
which outputs
```
3.11.2 (main, Mar  5 2023, 23:08:47) [Clang 13.1.6 (clang-1316.0.21.2.5)]
[/Users/iremaltan/.pyenv/versions/3.11.2/bin/python](https://file+.vscode-resource.vscode-cdn.net/Users/iremaltan/.pyenv/versions/3.11.2/bin/python)
```
I get no image when I use `jupyter notebook` either. Note that I had to add a kernel manually in `/Users/iremaltan/Library/Jupyter/kernels` to be able to use the same python version. Thus, when I try to run

```
jupyter-nbextension enable --py --sys-prefix nglview
```  
it looks for a python 3.9 and spits out `No module named 'nglview'`. What do I do? 

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
3.0.8

python -c 'import ipywidgets; print(ipywidgets.__version__)'
8.1.1
```

**Comment by sodiumnitrate** [comment]
Thank you for that. I know it's not installed in `3.9`, and I use the `3.11.2` kernel which can load the module. I had to downgrade notebook to a lower version [as described here](https://stackoverflow.com/questions/76893872/modulenotfounderror-no-module-named-notebook-base-when-installing-nbextension), and then run 

```
jupyter nbextensions_configurator enable --user
jupyter nbextension enable --py --sys-prefix widgetsnbextension
jupyter nbextension enable --py --sys-prefix nglview
```
It now creates a big enough window as a display area, but does not display any protein. I even tried creating a simple html file and viewing that -- I can see the stage but no protein. I'm not sure if I'm doing something obviously wrong, but here's the html:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>test</title>
    </head>
    <body>
        <script src="https://cdn.rawgit.com/arose/ngl/v2.0.0-dev.31/dist/ngl.js"></script>
        <script>
            var stage;
            document.addEventListener("DOMContentLoaded", function () {
              stage = new NGL.Stage("viewport");
              stage.loadFile("rcsb://1crn", {defaultRepresentation: true});
            });
          </script>
          <div id="viewport" style="width:800px; height:800px;"></div>
</body>
</html>
```
It just renders an 800x800 black box with no protein. This is similar to what I see in jupyter (a white box version anyway). Tried both firefox, safari, and chrome, but just a black box. [I can see the example codepen](https://codepen.io/pen?template=JNLMXb), just not anything local.

**Comment by hainm** [comment]
I don't really know how to debug then.
It's very straight forward to use `nglview` nowadays. 
Basically, you just need to do `pip install nglview` or `conda install nglview -c conda-forge` without any `enable` step in notebook or lab.

**Comment by sodiumnitrate** [comment]
Update: both jupyter notebook and vscode can load local files, but not fetch them from pdb using `show_pdbid`. The html version works when I change the file address to `"rcsb://1crn.pdb"`. Not sure if this is the intended behavior.

**Comment by hainm** [comment]
That `show_pdbid` issue should be fixed in https://github.com/nglviewer/nglview/pull/1086

**Comment by hainm** [comment]
Latest, v3.1.4, is supposed to work with VSCode.

<img width="1450" alt="image" src="https://github.com/user-attachments/assets/fafa1eca-efbe-4d82-866c-94cf6532477d">

**Comment by padiauj** [comment]
3.1.4 still appears to produce empty images for many pdb files: 

<img width="599" alt="image" src="https://github.com/user-attachments/assets/3478f89a-7fb8-46b7-94c8-f709bc46cb6e">

I think this could be a CIF parsing issue? https://github.com/nglviewer/ngl/pull/1001

**Comment by hainm** [comment]
Yeah, I have to use older version of ngl for vscode, newer version for lab. 

I will make another release soon that uses the same NGL latest version.

**Comment by hainm** [comment]
> Hi there, did this ever get fixed? I still can't seem to open .cif files in NGLviewers of any type (R or the general demo)

hi @njcaruana I think it's fixed in latest release of `nglview`. But you mentioned `R`, so I want to make sure `nglview` (this repo) is what you meant?
